name: Flutter SonarQube Scan
description: >
  Scan your Flutter code with SonarQube to detect Bugs, Vulnerabilities and Code Smells
branding:
  icon: check
  color: green
runs:
  using: docker
  image: Dockerfile
  entrypoint: "/entrypoint.sh"
  post-entrypoint: "/cleanup.sh"
inputs:
  args:
    description: Additional arguments to the sonar-scanner
    required: false
  projectBaseDir:
    description: Set the sonar.projectBaseDir analysis property
    required: false
    default: .
